repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Version of the pre-commit-hooks repo
    hooks:
      - id: trailing-whitespace
      exclude: '^.*$'
      - id: end-of-file-fixer
      - id: check-yaml
      - id: black  # For Python code formatting
